import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillTwitterCircle, AiFillLinkedin, AiFillGithub } from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Suyash Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>developedbySuyash with ❤</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=' cursor-pointer text-2xl' /></li>
              <li><a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 download-btn' href="resume.pdf" download>Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl text-teal-600 py-2 font-medium md:text-6xl'>Suyash</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Software Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>A software developer with a talent for resolving real-world issues. I can code in different
              coding languages and that is a plus point. Skilled in organizing multiple projects with
              extensive attention to detail and problem solving</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://twitter.com/suyash2297" target="_blank"><AiFillTwitterCircle /></a>
            <a href="https://www.linkedin.com/in/suyash-keshri-41143221a/" target="_blank"><AiFillLinkedin /></a>
            <a href="https://github.com/Suyash1507" target="_blank"><AiFillGithub /></a>
          </div>
          <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout="fill" objectFit='cover'></Image>
          </div>
        </section>
        <section>
          <div className=' text-center'>
            <h3 className='text-3xl py-1 my-5 dark:text-white'>Projects</h3>
            <p className=' text-md py-2 leading-8 text-gray-600 max-w-6xl mx-auto text-center text-xl'>
              Since the very beginning of my college I have done many projects in my academic career and also
              participated in different hackathons and below are some of my important projects.
            </p>
          </div>
          <div className=' lg:flex gap-10'>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'>Perforfamnce Evaluation of Cuda Based Ray Tracer</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/Suyash1507/CUDA-raytracer-main/tree/main/CUDA-raytracer-main" target="_blank">Project</a>
              <p className='py-2 '>Led a Team of 3 to develop a tool to check the performance of CUDA based
                ray tracer using distributed tracing</p>
              <h4 className=' py-4 text-teal-600'>Languages and Technologies I used</h4>
              <p className=' text-gray-800 py-1'>C++</p>
              <p className=' text-gray-800 py-1'>C</p>
              <p className=' text-gray-800 py-1'>VS code</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'>React based E-commerce website (Shopkart)</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/Suyash1507/Ecommerece-Website-Mern-Stack" target="_blank">Project</a>
              <p className='py-2'>Developed an complete fullstack ecommerce website</p>
              <h4 className=' py-4 text-teal-600'>Languages and Technologies I used</h4>
              <p className=' text-gray-800 py-1'>React JS</p>
              <p className=' text-gray-800 py-1'>Javascript and Express JS</p>
              <p className=' text-gray-800 py-1'>CSS</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2'>Sentiment Analysis using PRAW API</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://github.com/Suyash1507/Sentiment-Analysis-using-PRAW-API" target="_blank">Project</a>
              <p className='py-2'>Allowing for the real-time analysis of
                more than 1000 comments per minute using API.
              </p>
              <h4 className=' py-4 text-teal-600'>Languages and Technologies I used</h4>
              <p className=' text-gray-800 py-1'>Html</p>
              <p className=' text-gray-800 py-1'>Css</p>
              <p className=' text-gray-800 py-1'>Python</p>
            </div>
          </div>
        </section>
        <section>
          <div className='text-center'>
            <h3 className='text-3xl py-1 dark:text-white'>Technical Skills</h3>
            <p className=' text-md py-2 leading-8 text-gray-600 max-w-6xl mx-auto text-center text-xl'>
              Over the span of 4 years of my College I have also learned many different technical skills which is beneficial for working in any kind of Industry and in a software company if a person has different kind of skills then it will also benefit him as well as the company.
            </p>
            <div className=' lg:flex gap-10'>
              <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                <Image src={code} width={100} height={100} className="mx-auto"></Image>
                <h3 className='text-lg font-medium pt-8 pb-2'>Coding Languages</h3>
                <p className='py-2 '>Learned many different kinds of languages during the course of study which helped me in my academics</p>
                <h4 className=' py-4 text-teal-600'>Languages</h4>
                <p className=' text-gray-800 py-1'>C++</p>
                <p className=' text-gray-800 py-1'>Html and Css</p>
                <p className=' text-gray-800 py-1'>OOPS and My SQL</p>
              </div>
              <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                <Image src={code} width={100} height={100} className="mx-auto"></Image>
                <h3 className='text-lg font-medium pt-8 pb-2'>Data Structures and Algorithms</h3>
                <p className='py-2'>Also Worked on the following Data Structres and practiced on leetcode along with geeks for geeks</p>
                <h4 className=' py-4 text-teal-600'>Data Structures are</h4>
                <p className=' text-gray-800 py-1'>Linked List and Trees</p>
                <p className=' text-gray-800 py-1'>Hash Maps</p>
                <p className=' text-gray-800 py-1'>Dynamic Programming</p>
              </div>
              <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
                <Image src={code} width={100} height={100} className="mx-auto"></Image>
                <h3 className='text-lg font-medium pt-8 pb-2'>Web Technologies and Developer tools</h3>
                <p className='py-2'>Used many different kinds of web based technologies along with different kinds of developer tools
                </p>
                <h4 className=' py-4 text-teal-600'>These tools are as follows</h4>
                <p className=' text-gray-800 py-1'>Bootstarp and NodeJS</p>
                <p className=' text-gray-800 py-1'>React JS and Express JS</p>
                <p className=' text-gray-800 py-1'>VS code, Linux, Git, Github, Azure basics</p>
              </div>
            </div>
            <h3 className='text-3xl py-1 dark:text-white'>Certifications</h3>
          </div>

          <div className=' lg:flex gap-10'>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-md font-medium pt-8 pb-2'>AI Foundation by NASSCOM</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://1drv.ms/b/s!Ak1zweu8oWpxlyPtj8X3hs3EBo5o?e=tWfUQS" target="_blank">Certificate</a>
              <p className='py-2'>This course was about the basics of AI and how is it related to python</p>
              <h4 className=' py-4 text-teal-600'>Things I got to know about</h4>
              <p className=' text-gray-800 py-1'>History of AI</p>
              <p className=' text-gray-800 py-1'>Using different kinds of packages in python for AI</p>
              <p className=' text-gray-800 py-1'>Basics of coding in Python</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-md font-medium pt-8 pb-2'>Network and Communications</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://coursera.org/share/e08a9454c2dbd71aab0e0ffe03794e28" target="_blank">Certificate</a>
              <p className='py-2'>Helped me with the basics of networking along with different kinds of protocols used in networking</p>
              <h4 className=' py-4 text-teal-600'>Things I got to know about</h4>
              <p className=' text-gray-800 py-1'>Protocols in Networking</p>
              <p className=' text-gray-800 py-1'>Networking layers</p>
              <p className=' text-gray-800 py-1'>Communication</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-md font-medium pt-8 pb-2'>Web Development</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://foxmula.com/verify/QxRy1HrDD" target="_blank">Certificate</a>
              <p className='py-2'>Helped me in learning a lot of different web development fundamentals.
              </p>
              <h4 className=' py-4 text-teal-600'>Thiings I got to know about</h4>
              <p className=' text-gray-800 py-1'>Node JS</p>
              <p className=' text-gray-800 py-1'>HTML and CSS</p>
              <p className=' text-gray-800 py-1'>Express JS and MySQL</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-md font-medium pt-8 pb-2'>ARP Spoofing Fundamentals</h3>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="https://www.udemy.com/certificate/UC-51a62851-3cde-459e-9a3a-641f662aba86/" target="_blank">Certificate</a>
              <p className='py-2'>Tells us about the how the attack can be conducted with our own systems along with security vulnerabilities and it's protection.
              </p>
              <h4 className=' py-4 text-teal-600'>Things I got to know about</h4>
              <p className=' text-gray-800 py-1'>Vulnerabilities and how to exploit them</p>
              <p className=' text-gray-800 py-1'>Different kinds of ARP spoofing attacks</p>
              <p className=' text-gray-800 py-1'>Execution and Prevention of attacks</p>
            </div>
          </div>
          <footer class="flex flex-col items-center justify-between p-6 bg-white dark:bg-gray-900 sm:flex-row">
            <p class="text-sm text-gray-600 dark:text-gray-300 mx-auto">© Copyright 2022. All Rights Reserved. <br /> <br /> Contact me at hkeshri2011@gmail.com</p>
          </footer>
        </section>
      </main>

    </div>
  )
}
